### PR TITLE
Upgrade solidity coverage

### PR DESCRIPTION
**Pull request by nberger**

### CODE REVIEW

**Comment by nberger** [comment]
I'm not merging this yet because it keeps failing in travis with:

```
1) Contract: Market validation Mechanism should go through scenario with some claims and sells on the Market Maker:
     AssertionError: expected '9.999999999999999999999999999999999999999999999999999999999715998399999849121107e+78' to equal '9.999999999999999999999999999999999999999999999999999999999715998399999849217441e+78'
 ```

But when I run it locally it fails with a different error, the dreaded `NotFoundError: Key not found in database` from testrpc after which testrpc seems to die and that's it...

@AugustoL can you try running `npm run coverage` (or `yarn coverage`, I'm actually running with yarn) after doing `yarn install` on this branch and see what happens?

**Comment by nberger** [comment]
Now the build is green even though the coverage part is failing (the build doesn't fail because we made the coverage task to not fail the travis build in #178). We still have to fix the issue before merging this.

**Comment by cgewecke** [comment]
@nberger Is the test that's failing a test of someone's eth balance after sending to a fallback?

**Comment by nberger** [comment]
@cgewecke yes, it's a test of someone's eth balances, even though there's no fallback involved AFAICT. It's on a test that runs the following transaction: https://github.com/windingtree/LifToken/blob/9164e168837216d72ece26cab52bade06fd7d8ce/contracts/LifMarketValidationMechanism.sol#L234-L248. The assertion that fails is this one: https://github.com/windingtree/LifToken/blob/9164e168837216d72ece26cab52bade06fd7d8ce/test/MarketValidationMechanism.js#L219

**Comment by cgewecke** [comment]
Oh I think this is a bad bug in solidity-coverage that was discovered last week. I'm pushing a fix rn. Maybe upgrading one more step will make the problem go away :) What about the `invalid opcode` failure in the crowdsale test?

**Comment by cgewecke** [comment]
@nberger Maybe try bumping to `0.2.5`?

**Comment by nberger** [comment]
Yes, I'll try that and come back with the result. Thanks @cgewecke!

**Comment by nberger** [comment]
@cgewecke yes! it seems the test runs fine in 0.2.5, at least it does in my local env. Running in travis now 🤞

**Comment by nberger** [comment]
I'm going to merge this, thanks again @cgewecke!!

> What about the invalid opcode failure in the crowdsale test?

Which test are you referring to?

**Comment by cgewecke** [comment]
Oh I guess it's gone! I thought I saw that in the old travis run. Good
news, and sorry for the headaches with this.

**Pull request merged**
