### PR TITLE
Add missing Transfer and Approval events

### LINKED ISSUE #248: Missing Transfer events
Add Transfer events for `transferData` and `transferDataFrom` calls in LifToken. Consider also adding a Transfer event to address 0x0 in `burn` so wallets and block explorers (like etherscan) can show the right balances

### PR DESCRIPTION
**Pull request by nberger**
Added the events in the *Data methods, and in burn

Fixes #248

### CODE REVIEW

**Comment by nberger** [comment]
Don't we want to have an event that includes the data param? Using the original events only has the downside that they don't include that value

**Comment by AugustoL** [comment]
Yes, but the data parameter can be extracted from the transaction data, I think that will be better because if not we will log more information than the one we need. Ltes just use the ERC20 token events.

**Comment by nberger** [comment]
Makes sense, I'll change it that way

**Comment by nberger** [comment]
@AugustoL: just made the changes, how does it look now?

**Comment by AugustoL** [comment]
Great, thanks @nberger

**Pull request merged**
